dist: bionic

matrix:
  include:
    - name: PHP 7.2; Laravel 6; HTTPlug 1
      env:
        - PHP_VERSION=7.2
        - LARAVEL_VERSION=^6.0
        - PHPUNIT_VERSION=^8.5
        - HTTPPLUG_VERSION=^1.1
    - name: PHP 7.2; Laravel 6; HTTPlug 2
      env:
        - PHP_VERSION=7.2
        - LARAVEL_VERSION=^6.0
        - PHPUNIT_VERSION=^8.5
        - HTTPPLUG_VERSION=^2.0
    - name: PHP 7.2; Laravel 7; HTTPlug 1
      env:
        - PHP_VERSION=7.2
        - LARAVEL_VERSION=^7.0
        - PHPUNIT_VERSION=^8.5
        - HTTPPLUG_VERSION=^1.1
    - name: PHP 7.2; Laravel 7; HTTPlug 2
      env:
        - PHP_VERSION=7.2
        - LARAVEL_VERSION=^7.0
        - PHPUNIT_VERSION=^8.5
        - HTTPPLUG_VERSION=^2.0
    - name: PHP 7.3; Laravel 6; HTTPlug 1
      env:
        - PHP_VERSION=7.3
        - LARAVEL_VERSION=^6.0
        - PHPUNIT_VERSION=^9.0
        - HTTPPLUG_VERSION=^1.1
    - name: PHP 7.3; Laravel 6; HTTPlug 2
      env:
        - PHP_VERSION=7.3
        - LARAVEL_VERSION=^6.0
        - PHPUNIT_VERSION=^9.0
        - HTTPPLUG_VERSION=^2.0
    - name: PHP 7.3; Laravel 7; HTTPlug 1
      env:
        - PHP_VERSION=7.3
        - LARAVEL_VERSION=^7.0
        - PHPUNIT_VERSION=^9.0
        - HTTPPLUG_VERSION=^1.1
    - name: PHP 7.3; Laravel 7; HTTPlug 2
      env:
        - PHP_VERSION=7.3
        - LARAVEL_VERSION=^7.0
        - PHPUNIT_VERSION=^9.0
        - HTTPPLUG_VERSION=^2.0
    - name: PHP 7.4; Laravel 6; HTTPlug 1
      env:
        - PHP_VERSION=7.4
        - LARAVEL_VERSION=^6.0
        - PHPUNIT_VERSION=^9.0
        - HTTPPLUG_VERSION=^1.1
    - name: PHP 7.4; Laravel 6; HTTPlug 2
      env:
        - PHP_VERSION=7.4
        - LARAVEL_VERSION=^6.0
        - PHPUNIT_VERSION=^9.0
        - HTTPPLUG_VERSION=^2.0
    - name: PHP 7.4; Laravel 7; HTTPlug 1
      env:
        - PHP_VERSION=7.4
        - LARAVEL_VERSION=^7.0
        - PHPUNIT_VERSION=^9.0
        - HTTPPLUG_VERSION=^1.1
    - name: PHP 7.4; Laravel 7; HTTPlug 2
      env:
        - PHP_VERSION=7.4
        - LARAVEL_VERSION=^7.0
        - PHPUNIT_VERSION=^9.0
        - HTTPPLUG_VERSION=^2.0

before_install:
  - travis_retry docker pull registry.gitlab.com/grahamcampbell/php:$PHP_VERSION
  - docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint composer registry.gitlab.com/grahamcampbell/php:$PHP_VERSION require "laravel/framework:${LARAVEL_VERSION}" --no-update -n
  - docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint composer registry.gitlab.com/grahamcampbell/php:$PHP_VERSION require "phpunit/phpunit:${PHPUNIT_VERSION}" --dev --no-update -n
  - docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint composer registry.gitlab.com/grahamcampbell/php:$PHP_VERSION require "php-http/httplug:${HTTPPLUG_VERSION}" --no-update -n

install:
  - travis_retry docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint composer registry.gitlab.com/grahamcampbell/php:$PHP_VERSION install --no-suggest --prefer-dist -n -o

script:
  - docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint vendor/bin/phpunit registry.gitlab.com/grahamcampbell/php:$PHP_VERSION --coverage-clover build/logs/clover.xml

after_script:
  - travis_retry docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint ocular registry.gitlab.com/grahamcampbell/php:$PHP_VERSION code-coverage:upload --format=php-clover build/logs/clover.xml
